### ISSUE TITLE
Two ideas for MSBand-Simulator's future dev

### ISSUE THREAD

**Issue by mediaexplorer74** [Pdawg-bytes/MSBand-Simulator#1]
Hi!
Congradulations! You constructed nice MSBand-Simulator.
I have 2 ideas for future dev:
1) more UI animations and interactivity;
2) more App Logics, i.e. Fake Band data contolling (see https://github.com/BandOnTheRun/fake-band)

Best,
[m][e]

**Comment by Pdawg-bytes** [comment]
Hey! Thanks. About the animations, there really aren’t many. The UI of the band was pretty cut back due to its hardware limitations, and most things had no animation at all. I will work on app logic though, it does need some work. I’m planning on adding the ability to have the data controlling (like you mentioned), and also add more features to the apps. I’m gonna make the Bluetooth UI enable a fake Bluetooth status, and also the daily heart rate. I will also be adding the bands UI for step counting and heart rate. Lots of features coming, so stay tuned!

**Comment by mediaexplorer74** [comment]
Wow, you made the great progress at MSBand-Simulator developing :) Success! You are great C# developer. Cool =)
